name = "hono-hello-world"
main = "./src/index.ts"
compatibility_date = "2025-01-29"  # ✅ Add this if missing

[[d1_databases]]
binding = "DB"
database_name = "contacts_db"
database_id = "6d663581-85fe-4ce7-8f75-5c23548efb9d"
